# Generated by Django 4.0 on 2022-03-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=100)),
            ],
        ),
    ]
