# Generated by Django 4.0 on 2022-03-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
