# Generated by Django 4.0 on 2022-03-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aadhar_email_aadhar_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhar',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
