# Generated by Django 3.2.7 on 2022-03-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attendance_contractor_owner_project_violation_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
