# Generated by Django 4.0 on 2022-03-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220327_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
